function(build_plugin TARGET SRC)
    string(TOUPPER ${TARGET} UPPER_TARGET)
    if (BUILD_PLUGIN_${UPPER_TARGET})
        add_library(${TARGET} SHARED ${SRC})
        set_target_properties(${TARGET} PROPERTIES PREFIX "")
        target_link_libraries(${TARGET} PRIVATE intf)
    else(BUILD_PLUGIN_${UPPER_TARGET})
        message("can't build the plugin ${TARGET}, please check your deps or system")
    endif(BUILD_PLUGIN_${UPPER_TARGET})
endfunction(build_plugin TARGET SRC)
